export const PATH = {
  ROOT: "/",
  ALARM: "/alarm",
  SEARCHLIST: "/search",
  SEARCH_FILTER: "/search/filter",
  CREATE_TRIP: "/trip-new",
  SALE_LIST: "/my-page/sale-list",
  PURCAHSE_DETAIL: "/my-page/purchase-detail",
  SALE_DETAIL: "/my-page/sale-detail",
  DETAIL_ROOM: (productId?: number) => `/room/${productId ?? ":productId"}`,
  WRITE_TRANSFER: "/transfer/new",
  WRITE_TRANSFER_PRICE: "/transfer/new/price",
  WRITE_TRANSFER_SUCCESS: "/transfer/new/success",
  SIGNUP: "/signup",
  LOGIN: "/signin",
  MY_PAGE: "/my-page",
  SETTING: "/my-page/setting",
  MANAGE_PROFILE: "/my-page/setting/manage-profile",
  MANAGE_ACCOUNT: "/my-page/setting/manage-account",
  ACCOUNT_EDIT: "/my-page/setting/manage-account/edit",
  REDIRECT: "/auth/:provider",
  PASSWORD_RESET: "/password-reset",
  YANOLJA_ACCOUNT: "/account/yanolja",
  YANOLJA_ACCOUNT_VERIFICATION: "/account/yanolja/verify",
  YANOLJA_ACCOUNT_VERIFICATION_SUCCESS: "/account/yanolja/verify/success",
  RELOAD: 0,
  PAYMENT: (productId: string) => `/payment/${productId}`,
  PAYMENT_SUCCESS: (productId: string) => `/payment/${productId}/success`,
} as const;
